---

  - name: Install EPEL for RHEL9
    shell: 'dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -yy'
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "9"
      - epel_enabled
    args:
      warn: no

  - name: Install EPEL for RHEL8
    shell: 'dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -yy'
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"
      - epel_enabled
    args:
      warn: no
     
  - name: Download & install EPEL RPM for RHEL7
    shell: |
      cd /tmp
      wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      yum install epel-release-latest-7.noarch.rpm -yy
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
      - epel_installed.rc != 0
    args:
      warn: no  
            
  - name: Remove the EPEL RPM from RHEL7 host's /tmp
    file:
      path: /tmp/epel-release-latest-7.noarch.rpm
      state: absent
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
      - epel_installed.rc != 0      
      
  - name: Run YUM Update for RHEL7
    package:
      name: "*"
      state: latest
    ignore_errors: True      
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
                      
  - name: Run reposync - EPEL for RHEL7
    command: '{{ reposync7epel }}'  
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
    args:
      warn: no   
      
  - name: Run createrepo - EPEL for RHEL7
    command: '{{ crepo_workstation7 }}'
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
    args:
      warn: no
      
  - name: Get GPG key for EPEL for RHEL7
    shell: 'wget -O {{ repo_path }}/epel/RPM-GPG-KEY-EPEL-7 {{ epel7gpg }}'
    when: 
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
      - epel_enabled
    args:
      warn: no
                     
  - name: Run reposync - EPEL for RHEL8
    command: '{{ reposync8epel }}'  
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"
      - epel_enabled
    args:
      warn: no
            
  - name: Run createrepo - EPEL for RHEL8
    command: '{{ crepo_epel8 }}'    
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"
      - epel_enabled
    args:
      warn: no      
      
  - name: Get GPG key for EPEL for RHEL8
    shell: 'wget -O {{ repo_path }}/epel/RPM-GPG-KEY-EPEL-8 {{ epel8gpg }}'
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"
      - epel_enabled
    args:
      warn: no   

  - name: Run reposync - EPEL for RHEL9
    command: '{{ reposync9epel }}'  
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "9"
      - epel_enabled
    args:
      warn: no
            
  - name: Run createrepo - EPEL for RHEL9
    command: '{{ crepo_epel9 }}'    
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "9"
      - epel_enabled
    args:
      warn: no      
      
  - name: Get GPG key for EPEL for RHEL9
    shell: 'wget -O {{ repo_path }}/epel/RPM-GPG-KEY-EPEL-9 {{ epel9gpg }}'
    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "9"
      - epel_enabled
    args:
      warn: no               
