---
  - name: Update everything
    package:
      name: "*"
      state: latest

  - name: Install needed packages 
    package:
      name: 
        - httpd
        - createrepo
        - yum-utils  
        - openssh-server
        - openssh-clients 
        - python3
        - python3-pip
        - wget   
      state: latest
      
  - name: Install lsb-core - requires EPEL to be enabled!
    package:
      name: 
        - redhat-lsb-core
    when:
      - epel_enabled      
     
  - name: Install mod_ssl if applicable
    package:
      name:
        - mod_ssl
      state: latest
    when:
      - https_enabled or snakeoil_enabled
      
  
