# Simple playbook to keep your NC installation updated w/o using the webUI or ssh'ing into
# remote host


- hosts: NEXTCLOUD
  become: true
  become_method: sudo
  ignore_unreachable: true
  
  vars:
    occ: "sudo -u www-data php /var/www/nextcloud"
    #Provide path for your setup here. Note: Typically, sudo is not used, but for occ to work as expected, it was required.
    
  tasks:
  
  - name: Register hostname #Can be used for conditionals further in playbook, if needed.
    shell: hostname
    register: hostname
    args:
      warn: no 
 
  - name: Upgrade NC
    shell: '{{ occ }}/updater/updater.phar -q -n'
    args:
      warn: no
      
  - name: Set maintenance mode to off
    shell: '{{ occ }}/occ maintenance:mode --off'
    args:
      warn: no
